djcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads'))
]

leads/urls.py
from django.urls import path
from .views import lead_list, lead_detail, lead_create, lead_update, lead_delete

app_name = 'leads'

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('create/', lead_create, name='lead-create'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', lead_delete, name='lead-delete'),
]
 

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass
  

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

leads/forms.py
from django import forms
from .models import Lead

class LeadModelform(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent', 
        )

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

leads/views.py
from django.shortcuts import render, redirect
from .models import Lead, Agent
from .forms import LeadForm, LeadModelform


def lead_list(request):
    leads = Lead.objects.all()
    context = {
        'leads': leads
    }
    return render(request, 'leads/lead_list.html', context)


def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        'lead': lead
    }
    return render(request, 'leads/lead_detail.html', context)


def lead_create(request):
    form = LeadModelform()
    if request.method == 'POST':
        form = LeadModelform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        'form': form
    }
    return render(request, "leads/lead_create.html", context)


def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelform(instance=lead)
    if request.method == 'POST':
        form = LeadModelform(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/leads')
    context = {
        'form': form,
        'lead': lead
    }
    return render(request, 'leads/lead_update.html', context)


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')

    # def lead_update(request, pk):
    #     lead = Lead.objects.get(id=pk)
    #     form = LeadForm()
    #     if request.method == 'POST':
    #         form = LeadForm(request.POST)
    #         if form.is_valid():
    #             first_name = form.cleaned_data['first_name']
    #             last_name = form.cleaned_data['last_name']
    #             age = form.cleaned_data['age']
    #             lead.first_name = first_name
    #             lead.last_name = last_name
    #             lead.age = age
    #             lead.save()
    #             return redirect('/leads')
    #     context = {
    #         'form': form,
    #         'lead': lead
    #     }
    #     return render(request, 'leads/lead_update.html', context)

    # def lead_create(request):
    #     form = LeadForm()
    #     if request.method == 'POST':
    #         form = LeadForm(request.POST)
    #         if form.is_valid(): 
    #             first_name = form.cleaned_data['first_name']
    #             last_name = form.cleaned_data['last_name']
    #             age = form.cleaned_data['age']
    #             agent = Agent.objects.first()
    #             Lead.objects.create(
    #                 first_name=first_name,
    #                 last_name=last_name,
    #                 age=age,
    #                 agent=agent
    #             )
    #             return redirect('/leads')
    #     context = {
    #         'form': form
    #     }
    #     return render(request, "leads/lead_create.html", context)

leads/templates/leads/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM App</title>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

leads/templates/leads/home_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CRM App</title>
  </head>
  <body>
    <h1>All about leads</h1>
    <ul>
      {% for lead in leads %}
      <a href="/leads/{{ lead.pk }}/">
        <li>{{ lead.first_name }} {{ lead.last_name }}. Age: {{ lead.age }}</li>
      </a>
      {% endfor %}
    </ul>
  </body>
</html>

leads/templates/leads/lead_create.html
{% extends "leads/base.html" %}
{% block content %}
<a href="{% url 'leads:lead-list' %}">Go back to leads</a>
<hr />
<h1>Create a new lead</h1>
<form method="POST">
    {% csrf_token %} {{form.as_p}}
    <button type="submit">Submit</button>
</form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "leads/base.html" %}
{% block content %}
<a href="{% url 'leads:lead-list' %}">Go back to leads</a>
<hr />
<h1>This is the details of {{lead.first_name}}.</h1>
<p>This person's age : {{lead.age}}</p>
<p>The agent responsible for this lead : {{ lead.agent }}</p>
<hr />
<a href="{% url 'leads:lead-update' lead.pk %}">Update</a>
<a href="{% url 'leads:lead-delete' lead.pk %}">Delete</a>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "leads/base.html" %}
{% block content %}
<a href="{% url 'leads:lead-create' %}">Create a new lead</a>
<hr />
<h1>All about leads</h1>
<ul>
    {% for lead in leads %}
    <a href="{% url 'leads:lead-detail' lead.pk %}">
        <li>{{ lead.first_name }} {{ lead.last_name }}. Age: {{ lead.age }}</li>
    </a>
    {% endfor %}
</ul>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "leads/base.html" %}
{% block content %}
<a href="{% url 'leads:lead-detail' lead.pk %}">Go to {{ lead.first_name }} {{ lead.last_name }} detail</a>
<hr />
<h1>Update lead : {{ lead.first_name }} {{ lead.last_name }}</h1>
<form method="POST">
    {% csrf_token %} {{form.as_p}}
    <button type="submit">Submit</button>
</form>
{% endblock content %}